# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'
    groups:
      npm:
        patterns: ['*'] # grouping all to avoid PR noise
        exclude-patterns: ['@microsoft/applicationinsights-*'] # these are often buggy so we keep them separate below
      application-insights:
        patterns: ['@microsoft/applicationinsights-*']
    ignore:
      - dependency-name: recharts
        update-types: [version-update:semver-major] # shadcn still doesn;t support (https://github.com/shadcn-ui/ui/issues/7669)

  - package-ecosystem: 'dotnet-sdk'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'

  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'
    groups:
      nuget:
        patterns: ['*'] # grouping all to avoid PR noise
