manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: d41716f63c5c86c811e06559c25a668a9beb1d5a
      clone-depth: 1
      import:
        path-prefix: external
