#ifndef KORRA_CONFIGS_WIFI_H
#define KORRA_CONFIGS_WIFI_H

#ifdef ARDUINO_ARCH_ESP32
#define CONFIG_BOARD_HAS_WIFI 1
#endif

#ifdef CONFIG_BOARD_HAS_WIFI
// The amount of time to wait for a WiFi connection before rebooting
#define CONFIG_WIFI_CONNECTION_REBOOT_TIMEOUT_SEC 30

#if (defined(CONFIG_WIFI_ENTERPRISE_USERNAME) && !defined(CONFIG_WIFI_ENTERPRISE_PASSWORD)) || \
    (!defined(CONFIG_WIFI_ENTERPRISE_USERNAME) && defined(CONFIG_WIFI_ENTERPRISE_PASSWORD))
#error "Enterprise WIFI (802.1x) requires both username and password"
#endif

#ifndef CONFIG_WIFI_PASSPHRASE
#define CONFIG_WIFI_PASSPHRASE nullptr
#endif // CONFIG_WIFI_PASSPHRASE

#ifndef CONFIG_WIFI_ENTERPRISE_IDENTITY
#define CONFIG_WIFI_ENTERPRISE_IDENTITY ""
#endif // CONFIG_WIFI_ENTERPRISE_IDENTITY

#ifndef CONFIG_WIFI_ENTERPRISE_USERNAME
#define CONFIG_WIFI_ENTERPRISE_USERNAME nullptr
#endif // CONFIG_WIFI_ENTERPRISE_USERNAME

#ifndef CONFIG_WIFI_ENTERPRISE_PASSWORD
#define CONFIG_WIFI_ENTERPRISE_PASSWORD nullptr
#endif // CONFIG_WIFI_ENTERPRISE_PASSWORD

#endif // BOARD_HAS_WIFI

#endif // KORRA_CONFIGS_WIFI_H
