name: Firmware

on:
  push:
    # branches: [main]
    tags: ['firmware*']
    paths:
      - firmware/**
      - west-manifest/**
      - .west/**
      - .github/workflows/firmware.yml
  pull_request:
    branches: [main]
    paths:
      - firmware/**
      - west-manifest/**
      - .west/**
      - .github/workflows/firmware.yml
  workflow_dispatch:

permissions:
  contents: write # write required for ncipollo/release-action to create a release
  attestations: write # required for actions/attest-build-provenance
  id-token: write # required for actions/attest-build-provenance

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    # using macos-latest because it tends to be faster and closely mirrors dev environment
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          # cache: 'pip' # cache works when there is a requirements.txt, pyproject.toml, poetry.lock or pipfile.lock

      - name: Set up Zephyr SDK
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: ${{ github.workspace }}/west-manifest
          toolchains: arm-zephyr-eabi:xtensa-espressif_esp32s3_zephyr-elf

      - name: Build (ESP32-S3-DevKitC-1, keeper)
        run: >
          west build firmware
          --board esp32s3_devkitc/esp32s3/procpu
          --pristine
          --build-dir firmware/build/keeper/esp32s3_devkitc
          -DEXTRA_DTC_OVERLAY_FILE='apps/keeper.overlay'
          -DEXTRA_CONF_FILE='apps/keeper.conf'

      - name: Build (FRDM-RW612, keeper)
        run: >
          west build firmware
          --board esp32s3_devkitc/esp32s3/procpu
          --pristine
          --build-dir firmware/build/keeper/frdm_rw612
          -DEXTRA_DTC_OVERLAY_FILE='apps/keeper.overlay'
          -DEXTRA_CONF_FILE='apps/keeper.conf'

      - name: Build (ESP32-S3-DevKitC-1, pot)
        run: >
          west build firmware
          --board esp32s3_devkitc/esp32s3/procpu
          --pristine
          --build-dir firmware/build/pot/esp32s3_devkitc
          -DEXTRA_DTC_OVERLAY_FILE='apps/pot.overlay'
          -DEXTRA_CONF_FILE='apps/pot.conf'

      - name: Build (FRDM-RW612, pot)
        run: >
          west build firmware
          --board esp32s3_devkitc/esp32s3/procpu
          --pristine
          --build-dir firmware/build/pot/frdm_rw612
          -DEXTRA_DTC_OVERLAY_FILE='apps/pot.overlay'
          -DEXTRA_CONF_FILE='apps/pot.conf'

      - name: Collect output
        run: |
          mkdir -p binaries && \

          cp firmware/build/keeper/esp32s3_devkitc/zephyr/zephyr.bin binaries/keeper-esp32s3_devkitc.bin && \
          cp firmware/build/keeper/esp32s3_devkitc/zephyr/zephyr.elf binaries/keeper-esp32s3_devkitc.elf && \

          cp firmware/build/keeper/frdm_rw612/zephyr/zephyr.bin binaries/keeper-frdm_rw612.bin && \
          cp firmware/build/keeper/frdm_rw612/zephyr/zephyr.elf binaries/keeper-frdm_rw612.elf && \

          cp firmware/build/pot/esp32s3_devkitc/zephyr/zephyr.bin binaries/pot-esp32s3_devkitc.bin && \
          cp firmware/build/pot/esp32s3_devkitc/zephyr/zephyr.elf binaries/pot-esp32s3_devkitc.elf && \

          cp firmware/build/pot/frdm_rw612/zephyr/zephyr.bin binaries/pot-frdm_rw612.bin && \
          cp firmware/build/pot/frdm_rw612/zephyr/zephyr.elf binaries/pot-frdm_rw612.elf && \

          echo 'Done'

      - name: Upload Artifact (binaries)
        uses: actions/upload-artifact@v4
        with:
          path: binaries
          name: binaries
          retention-days: 1

      - name: Provenance Attestation
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.repository.public }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ github.workspace }}/binaries/*.bin

      - name: Upload Release Artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ github.workspace }}/binaries/*.bin'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          tag: ${{ github.ref_name }}

      # a web endpoint can be triggered at this point to push to devices
