name: Firmware

on:
  push:
    # branches: [main]
    tags: ['firmware*']
    paths:
      - firmware/**
      - west-manifest/**
      - .west/**
      - .github/workflows/firmware.yml
  pull_request:
    branches: [main]
    paths:
      - firmware/**
      - west-manifest/**
      - .west/**
      - .github/workflows/firmware.yml
  workflow_dispatch:

permissions:
  contents: write # write required for ncipollo/release-action to create a release
  attestations: write # required for actions/attest-build-provenance
  id-token: write # required for actions/attest-build-provenance

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    # using macos-latest because it tends to be faster and closely mirrors dev environment
    runs-on: macos-latest
    timeout-minutes: 15
    if: ${{ !contains(github.actor, '[bot]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          # cache: 'pip' # cache works when there is a requirements.txt, pyproject.toml, poetry.lock or pipfile.lock

      - name: Set up Zephyr SDK
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: ${{ github.workspace }}/west-manifest
          toolchains: arm-zephyr-eabi:xtensa-espressif_esp32s3_zephyr-elf

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Download deps
        run: pnpm install
        working-directory: '${{ github.workspace }}/firmware'

      - name: Fetch Blobs
        run: pnpm blobs:fetch
        working-directory: '${{ github.workspace }}/firmware'

      - name: Build
        run: pnpm build
        working-directory: '${{ github.workspace }}/firmware'

      - name: Collect output
        run: pnpm collect
        working-directory: '${{ github.workspace }}/firmware'

      - name: Upload Artifact (binaries)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/firmware/binaries
          name: binaries
          retention-days: 1

      - name: Provenance Attestation
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.repository.public }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ github.workspace }}/firmware/binaries/*.bin

      - name: Upload Release Artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ github.workspace }}/firmware/binaries/*.bin'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          tag: ${{ github.ref_name }}

      # a web endpoint can be triggered at this point to push to devices
