name: Infrastructure

on:
  push:
    branches: [main]
    paths:
      - deploy/**
      - .github/workflows/iac.yml
  pull_request:
    branches: [main]
    paths:
      - deploy/**
      - .github/workflows/iac.yml
  workflow_dispatch:

permissions:
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: ${{ (github.event_name == 'pull_request' && 'Validate') || 'Deploy' }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false # let the current one finish before starting a new one

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload Artifact (deploy)
        uses: actions/upload-artifact@v4
        with:
          path: deploy
          name: deploy
          retention-days: 1

      - name: Azure Login
        if: ${{ !contains(github.actor, '[bot]') }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Azure Resources
        if: ${{ !contains(github.actor, '[bot]') && github.event_name == 'pull_request' }}
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: '${{ github.workspace }}/deploy/main.bicep'
          scope: 'resourcegroup'
          deploymentMode: 'Validate'
          deploymentName: 'main-pr${{ github.event.number }}' # allows for concurrent validation

      - name: Deploy Azure Resources
        if: ${{ !contains(github.actor, '[bot]') && github.event_name != 'pull_request' }}
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: '${{ github.workspace }}/deploy/main.bicep'
          scope: 'resourcegroup'
