name: Remove Review Resources

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths-ignore:
      - .devcontainer/**
      - .vscode/**
      - docs/**
      - README.md
      - LICENSE
  workflow_dispatch:
    inputs:
      pr:
        description: 'Pull request number'
        required: true
        type: number

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  contents: read

jobs:
  Remove:
    if: ${{ !contains(github.actor, '[bot]') && !contains(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Remove SWA environment (website)
        uses: azure/static-web-apps-deploy@v1
        if: ${{ github.event_name == 'pull_request' }}
        continue-on-error: true # Ignore errors when the SWA does not exist
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN_WEBSITE }}
          action: 'close'
          app_location: ''

      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Remove review resources
      #   run: |
      #     dotnet tool install --global azure-resources-cleaner && \
      #     azrc \
      #     --pr ${{ inputs.pr || github.event.pull_request.number }} \
      #     --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}
