name: Tinybird

on:
  push:
    branches: [main]
    paths:
      - tinybird/**
      - .github/workflows/tinybird.yml
  pull_request:
    branches: [main]
    paths:
      - tinybird/**
      - .github/workflows/tinybird.yml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TINYBIRD_HOST: 'https://api.europe-west2.gcp.tinybird.co'
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      tinybird:
        image: tinybirdco/tinybird-local:latest
        ports:
          - 7181:7181

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Upload Artifact (tinybird)
        uses: actions/upload-artifact@v4
        with:
          path: tinybird
          name: tinybird
          retention-days: 1

      - name: Install Tinybird CLI
        run: curl https://tinybird.co | sh

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Download deps
        run: pnpm install
        working-directory: '${{ github.workspace }}/tinybird'

      - name: Build project
        if: ${{ github.ref != 'refs/heads/main' }}
        run: pnpm build
        working-directory: '${{ github.workspace }}/tinybird'

      - name: Test project
        if: ${{ github.ref != 'refs/heads/main' }}
        run: pnpm test
        working-directory: '${{ github.workspace }}/tinybird'

      - name: Deployment check
        if: ${{ github.ref != 'refs/heads/main' }}
        run: pnpm tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deploy --check
        working-directory: '${{ github.workspace }}/tinybird'

      - name: Deploy project
        if: ${{ github.ref == 'refs/heads/main' }}
        run: pnpm tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deploy
        # run: pnpm tb --cloud deploy --allow-destructive-operations
        working-directory: '${{ github.workspace }}/tinybird'
