name: PlatformIO Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 2 * *' # Runs at 01:00 on the second day of the month

permissions:
  contents: read

jobs:
  Updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID_RELEASER }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY_RELEASER }}
          permission-contents: write
          permission-pull-requests: write

      - name: Update
        uses: peterus/platformio_dependabot@v1
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
