name: PlatformIO Updates

on:
  schedule:
    - cron: '0 1 2 * *' # Runs at 01:00 on the second day of the month
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  Updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update
        uses: peterus/platformio_dependabot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
