name: PlatformIO Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 2 * *' # Runs at 01:00 on the second day of the month

permissions:
  contents: read

jobs:
  Updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          # cache: 'pip' # cache works when there is a requirements.txt, pyproject.toml, poetry.lock or pipfile.lock

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID_RELEASER }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY_RELEASER }}
          permission-contents: write
          permission-pull-requests: write

      - name: Update
        uses: peterus/platformio_dependabot@v1
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
