name: Website

on:
  workflow_dispatch:
  # these is commented out because SWA turned out messy so I set up on Vercel. I might restore it when/if I have time.
  # push:
  #   branches: [main]
  #   tags: ['website@*']
  #   paths:
  #     - 'website/**'
  #     - '.github/workflows/website.yml'
  pull_request:
    branches: [main]
    paths:
      - 'website/**'
      - '.github/workflows/website.yml'

permissions:
  contents: read
  pull-requests: write # required to write PR comment

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # wait for previous runs to complete on main and tags
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

env:
  NEXT_TELEMETRY_DISABLED: 1 # Disable Next.js telemetry

  # SWA_ENVIRONMENT_FOR_PR: ${{ (github.event_name == 'pull_request' && format('ra{0}', github.event.pull_request.number)) || '' }}
  SWA_ENVIRONMENT_FOR_PR: ${{ (github.event_name == 'pull_request' && format('{0}', github.event.pull_request.number)) || '' }}

  GITHUB_SHA: ${{ github.sha }} # not discovered by default
  GITHUB_REF_NAME: ${{ github.ref_name }} # not discovered by default
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  Website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Download deps
        run: pnpm install
        working-directory: '${{ github.workspace }}/website'

      - name: Restore .next/cache
        id: cache-next-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/website/.next/cache
          key: ${{ runner.os }}-next-website-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-website

      - name: Build
        run: pnpm build
        working-directory: '${{ github.workspace }}/website'

      - name: Lint
        run: pnpm lint
        working-directory: '${{ github.workspace }}/website'

      - name: Azure Login
        if: ${{ !contains(github.actor, '[bot]') }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # https://github.com/Azure/static-web-apps/issues/1059#issuecomment-1638817705
      # https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#enable-standalone-feature
      # https://medium.com/@wdedweliwaththa/the-ultimate-guide-to-deploying-next-js-a1501de3e4d0
      - name: Copy standalone output files
        run: |
          cp -r .next/standalone/website/. .next/standalone && \
          cp -r .next/static .next/standalone/.next/ && \
          cp -r public .next/standalone/ && \
          echo 'Done'
        working-directory: website

      - name: Deploy to SWA
        if: ${{ !contains(github.actor, '[bot]') }}
        id: swa
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN_WEBSITE }}
          # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: 'upload'
          app_location: 'website'
          deployment_environment: ${{ env.SWA_ENVIRONMENT_FOR_PR }}
          skip_app_build: true
          skip_api_build: true
        env:
          NODE_VERSION: 24

      - name: Set app settings for SWA # bear in mind that this creates or updates but does not remove
        uses: azure/cli@v2
        if: ${{ !contains(github.actor, '[bot]') }}
        with:
          inlineScript: >
            az staticwebapp appsettings set
            --resource-group ${{ env. RESOURCE_GROUP }}
            --name korra
            --environment-name '${{ env.SWA_ENVIRONMENT_FOR_PR }}'
            --setting-names ${{ env.SWA_SETTINGS }}
        env:
          # Some settings are here because we cannot use Managed Identity on the free tier of SWA
          SWA_SETTINGS: >
            GITHUB_SHA="${{ github.sha }}"
            GITHUB_REF_NAME="${{ github.ref_name }}"
            DATABASE_URL="${{ secrets.DATABASE_URL }}"
            IOT_HUB_CONNECTION_STRING="${{ secrets.IOT_HUB_CONNECTION_STRING }}"
            PROCESSOR_API_KEY="${{ secrets.PROCESSOR_API_KEY }}"
            FIRMWARE_API_KEY="${{ secrets.FIRMWARE_API_KEY }}"

      - name: Publish review app URLs
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ !contains(github.actor, '[bot]') && github.event_name == 'pull_request' }}
        with:
          message: |
            Review App for `website` succeeded.
            [Preview](${{ steps.swa.outputs.static_web_app_url }})
          comment-tag: website

      - name: Save .next/cache
        if: always() && steps.cache-next-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/website/.next/cache
          key: ${{ steps.cache-next-restore.outputs.cache-primary-key }}
